### ISSUE TITLE
Auto expiring coupon codes

### ISSUE THREAD

**Issue by kalenjordan** [magento-hackathon/Hackathon_PromoCodeMessages#1]
One thing that I'd like to figure out is a way to do better error messages for the auto expiring coupon codes that MageMail uses.  Not exactly sure the best place for the logic to live but here's how it works right now.

The `salesrule_coupon` table which stores the individual coupon codes happens to have an `expiration_date` field per each coupon.  Handy right?  However, it doesn't actually work.  At least as of the last time I tested it.

![screen shot 2015-07-24 at 11 48 58 am](https://cloud.githubusercontent.com/assets/1542197/8882775/72001bb0-31fe-11e5-8445-2b83d1314994.png)

So, when I implemented auto expiring coupon codes in MageMail, the way that I "expire" a coupon code is simply to mark it as used by setting the `times_used` field.  That seems to be the only way to invalidate an individual coupon code, without writing some additional custom logic to hook into Magento's coupon code validation.

So, the way that Hackathon_PromoCodeMessages would handle an auto expired coupon code would be probably to say "this coupon code has already been used", which is obviously misleading.

I'm trying to figure out the best way to approach this.  Few ideas:
- Bake some custom logic into the MageMail extension that can cause Magento to respect the individual `expiration_date` field.  Not in love with this option because I like to keep the MageMail extension suuuper lightweight - it doesn't even have any observers currently.
- Create a separate standalone module with the sole purpose of fixing the `expiration_date` field
- Add some logic to this module (Hackathon_PromoCodeMessages) to fix the `expiration_date` field.

What say you, @lfolco ?

**Comment by lfolco** [comment]
I can look into option #3, since you're actively promoting this module. also, i object to the phrase "skin this cat" for obvious reasons.

**Comment by kalenjordan** [comment]
ahem...I meant to say "approach this cat".

**Comment by kalenjordan** [comment]
Yes I like the idea of #3.  My only concern was that changing the way discounts work as opposed to just improving error messages kind of fundamentally changes the scope of this module.

There's something beautiful about the simplicity of only touching error messages.  And that also makes me worry less about potential conflicts with other extensions.

**Comment by lfolco** [comment]
that's a good point. if you go that route, then option 1 seems to make the most sense; it keeps the separation of concerns intact.

**Comment by kalenjordan** [comment]
Thinking more about this and I'm starting to lean towards the following.
- Add a `magemail_expired_at` column to the `salesrule_coupon` table.
- Bake some logic into this extension to look for that field and if present and non-null give a specific error message about it.

One thing I like about that is that is that you already have all of the mechanisms in place to intercept error messages in this extension.  It's not quite as decoupled as option #2 but I'm not entirely sure whether there could be side effects to changing the way the core expiration_date field works.

If that sounds good, I'll PR it.

**Comment by lfolco** [comment]
you'd add the magemail column in the magemail extension, or to this? (i.e., which extension would have the db update migration?)

**Comment by kalenjordan** [comment]
I'd add the column from the magemail extension.  Promo codes would just look at it's value if it was there.

**Comment by lfolco** [comment]
sounds good!

**Comment by kalenjordan** [comment]
Boomtown.  https://github.com/magento-hackathon/Hackathon_PromoCodeMessages/pull/2
