### ISSUE TITLE
Times are taken in consideration when comparing dates

### ISSUE THREAD

**Issue by digitalpianism** [magento-hackathon/Hackathon_PromoCodeMessages#11]
Thus, if you have a coupon that expieres on today's date, user will get a "coupon expired on today's date" error message whereas it's totally valid on a native Magento install.

**Comment by Zifius** [comment]
Hi @digitalpianism,

I actually submitted a PR for this some time ago: #10

Not sure it's the best one, just didn't found a way to compare dates without the time part

Cheers,
Alex

**Comment by digitalpianism** [comment]
@Zifius yeah I noticed your PR it's kind of hacky so I made another PR which is cleaner ;)

**Comment by Zifius** [comment]
Makes sense, I closed my PR :)

**Comment by lfolco** [comment]
Can you give me steps to reproduce this error? I setup a cart rule that expires today, but the validation is passing:

![image](https://cloud.githubusercontent.com/assets/1709329/15684191/fb493b42-2733-11e6-8d0e-1f0a51291f0a.png)

**Comment by digitalpianism** [comment]
@lfolco here's how to replicate it:

create a coupon that expires today.
Make it usable one time and use it so it can't pass this test:

```
        if ($coupon->getUsageLimit() && $coupon->getTimesUsed() >= $coupon->getUsageLimit()) {
            Mage::throwException($this->_formatMessage(
                'Your coupon was already used.',
                $coupon->getUsageLimit(),
                sprintf('It may only be used %d time(s).', $coupon->getUsageLimit())
            ));
        }
```

Now try to apply that coupon to another cart.

Instead of getting the **Your coupon was already used. It may only be used %d times** error message you will get the **Your coupon is no longer valid. It expired on %s.** error message.

That's because the date comparison is taking times in the calculation, the PR I made fixes it.

**Comment by lfolco** [comment]
Awesome, thanks!
