### ISSUE TITLE
Apply the rule only to cart items matching the following conditions

### ISSUE THREAD

**Issue by uandiweb** [magento-hackathon/Hackathon_PromoCodeMessages#13]
Hi,

Under the "Actions" tab, there is an option to exclude some items. I added one manufacturer to be excluded from discounts. When I test it on the cart page, I don't get a custom message. Is it possible to make the extension work with the "Action" exclusion, just like with the "Conditions" exclusions?

Thank you

**Comment by lfolco** [comment]
That is something that we have on our ToDo list, but haven't implemented yet.

**Comment by lfolco** [comment]
This is fixed.
