### ISSUE TITLE
Exclude a Brand

### ISSUE THREAD

**Issue by uandiweb** [magento-hackathon/Hackathon_PromoCodeMessages#14]
I've created the following rule in order to exclude UGG products from the coupon:

If ALL  of these conditions are TRUE :
If an item is NOT FOUND  in the cart with ALL  of these conditions true: 
Brand  is  UGG

When I add an UGG product to cart, and try to use the coupon it says:

All of the following conditions must be met:
Brand must be UGG.

It should actually say (2nd line): Brand must <b>NOT</b> be UGG.

This extension is a must. Thank you for the good work.

**Comment by lfolco** [comment]
This is fixed.
